--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/NurAzliYT/InfoUI
build-by-default: true
branches:
- main
projects:
  InfoUI:
    path: ""
libs:
src: jojoe77777/FormAPI/libFormAPI
...
