---
name: InfoUI
main: NurAzliYT\InfoUI\Loader
version: 1.0.1
api: 5.3.0
author: NurAzliYT
description: "See info such as About, Staff, Update, Rules Form UI"

commands:
  info:
    description: "Open InfoUI"
    permission: infoui.command
    
permissions:
  infoui.command:
    description: "InfoUI Perm"
    default: true
...
