---
name: InfoUI
main: Riza\InfoUI\Loader
version: 1.0.0
api: 5.0.0
author: Riza
description: "See info such as About, Staff, Update, Rules"

commands:
  info:
    description: "Open InfoUI"
    permission: info.rz
    
permissions:
  info.rz:
    description: "InfoUI Perm"
    default: true
...